import InputGenerator from './InputGenerator';
import Validator from './Validator';

test('basic', () => {
    const generator = new InputGenerator();
    const output = generator.generate();

    expect(output).toBeTruthy();
});

test('validation', async () => {
    const input = 'This this that that\nNo Yes Why Okay\nOh No Yes\n Yes Yes Yes Yes';
    const validator = new Validator();

    expect(await validator.validate(input, '2')).toBeTruthy();
});

test('validation false', async () => {
    const input = 'This this that that\nNo Yes Why Okay\nOh No Yes\n Yes Yes Yes Yes';
    const validator = new Validator();

    expect(await validator.validate(input, '3')).toBeFalsy();
});

test('intput validation', async () => {
    const generator = new InputGenerator();
    const validator = new Validator();

    const data = generator.generate();
    const result = await validator.validate(data, '5');

    expect(result).toBeFalsy();
});

test('temp', async (asd) => {
    const validator = new Validator();
    const result = await validator.validate(testData, '305');

    expect(result).toBe(true);
})




const testData = `uckiowh gad gad baytyk ubvug gad
baytyk mmg rclqxu aahanv fpe gad
msykuiq ivdtx wqtwtva dioxc uckiowh eibkxou
huvmxfh nerg baytyk uckiowh nerg gvppcxp
huvmxfh aahanv mmg nerg jbe fpe
rclqxu dioxc gvppcxp msykuiq mmg dioxc
baytyk wqtwtva fpe ivdtx wqtwtva fpe
ettc eibkxou wqtwtva msykuiq ivdtx uckiowh
msykuiq baytyk gad msykuiq huvmxfh msykuiq
dnw gvppcxp aahanv gvppcxp baytyk huvmxfh
ettc huvmxfh aahanv gad fpe msykuiq
ivdtx jbe ubvug uckiowh aahanv dnw
ubvug rclqxu jbe gad eibkxou dioxc
jbe rclqxu gvppcxp gvppcxp gad eibkxou
rclqxu aahanv uckiowh ettc rclqxu msykuiq
ubvug wqtwtva huvmxfh uckiowh mmg eibkxou
wqtwtva gvppcxp mmg ettc ettc dioxc
aahanv ivdtx aahanv nerg mmg dioxc
wqtwtva baytyk ubvug dnw fpe gad
nerg fpe mmg msykuiq fpe fpe
eibkxou ettc mmg rclqxu dioxc nerg
dnw msykuiq gad fpe eibkxou ubvug
dioxc eibkxou rclqxu wqtwtva baytyk ubvug
ivdtx baytyk ettc gvppcxp aahanv msykuiq
aahanv rclqxu ubvug ivdtx gvppcxp aahanv
gad gvppcxp nerg ettc aahanv ettc
ivdtx msykuiq ettc mmg gad msykuiq
ubvug msykuiq mmg wqtwtva dnw uckiowh
baytyk wqtwtva uckiowh nerg mmg dnw
fpe msykuiq baytyk ettc eibkxou ubvug
fpe ivdtx rclqxu dioxc dioxc jbe
gad baytyk uckiowh rclqxu wqtwtva ettc
huvmxfh fpe nerg gvppcxp wqtwtva ettc
fpe jbe jbe nerg dnw eibkxou
wqtwtva fpe ubvug ettc aahanv gvppcxp
ubvug ettc eibkxou ettc huvmxfh nerg
dioxc ivdtx huvmxfh wqtwtva ubvug huvmxfh
dnw eibkxou gvppcxp huvmxfh nerg dnw
ubvug jbe ivdtx aahanv ubvug fpe
fpe gad nerg uckiowh dioxc wqtwtva
nerg gad nerg ubvug aahanv ivdtx
gad nerg mmg dnw aahanv ivdtx
dnw ivdtx jbe nerg nerg wqtwtva
gad gvppcxp ettc msykuiq dnw mmg
uckiowh rclqxu aahanv uckiowh msykuiq baytyk
jbe baytyk ettc ettc dioxc mmg
ubvug aahanv ettc baytyk ubvug ubvug
msykuiq ubvug nerg dnw msykuiq ivdtx
mmg ubvug gvppcxp gvppcxp nerg wqtwtva
fpe rclqxu nerg dioxc wqtwtva ettc
aahanv rclqxu msykuiq jbe gad uckiowh
uckiowh wqtwtva dioxc gvppcxp ivdtx jbe
gvppcxp gad wqtwtva gad uckiowh ettc
dioxc baytyk ubvug huvmxfh mmg huvmxfh
rclqxu ettc gad aahanv ettc huvmxfh
nerg ivdtx aahanv nerg gad dioxc
msykuiq fpe gad ivdtx ivdtx msykuiq
gvppcxp ubvug ivdtx ettc fpe uckiowh
ettc gvppcxp ivdtx wqtwtva huvmxfh aahanv
mmg gad eibkxou eibkxou dioxc huvmxfh
wqtwtva ivdtx rclqxu rclqxu mmg ettc
uckiowh ubvug ivdtx nerg jbe fpe
aahanv fpe wqtwtva huvmxfh fpe fpe
aahanv huvmxfh fpe mmg aahanv nerg
baytyk dioxc wqtwtva ubvug uckiowh aahanv
jbe ivdtx aahanv dnw dnw dioxc
huvmxfh rclqxu gvppcxp msykuiq nerg uckiowh
jbe ivdtx ettc mmg ettc wqtwtva
mmg gad huvmxfh gad gvppcxp jbe
nerg eibkxou uckiowh ettc mmg ettc
huvmxfh wqtwtva nerg baytyk fpe fpe
dioxc mmg mmg ivdtx fpe dnw
jbe ubvug huvmxfh ettc ettc nerg
ubvug mmg mmg ettc uckiowh nerg
gad jbe wqtwtva fpe rclqxu ettc
dnw rclqxu nerg msykuiq mmg gvppcxp
uckiowh uckiowh mmg uckiowh eibkxou jbe
wqtwtva eibkxou baytyk ivdtx wqtwtva dioxc
gad ubvug gad fpe ivdtx fpe
uckiowh fpe ettc rclqxu dnw dnw
huvmxfh baytyk wqtwtva nerg ubvug jbe
msykuiq wqtwtva ubvug uckiowh uckiowh uckiowh
jbe eibkxou msykuiq dnw gad baytyk
uckiowh ettc ubvug gad baytyk fpe
baytyk huvmxfh dnw uckiowh eibkxou baytyk
gad gvppcxp uckiowh fpe gvppcxp jbe
mmg ubvug msykuiq dnw jbe gvppcxp
gvppcxp mmg gad ivdtx eibkxou ivdtx
ettc ubvug rclqxu nerg rclqxu baytyk
nerg dioxc dnw jbe aahanv ivdtx
msykuiq ivdtx baytyk gvppcxp huvmxfh gvppcxp
ubvug nerg uckiowh rclqxu uckiowh mmg
aahanv wqtwtva rclqxu ettc ettc dnw
msykuiq jbe baytyk nerg huvmxfh fpe
fpe baytyk dnw mmg baytyk aahanv
ubvug jbe fpe jbe gvppcxp rclqxu
fpe wqtwtva gad fpe dnw mmg
rclqxu gad dioxc eibkxou aahanv ettc
nerg huvmxfh dioxc ivdtx wqtwtva huvmxfh
mmg jbe jbe dnw gad rclqxu
aahanv rclqxu rclqxu mmg gad ivdtx
baytyk ubvug gvppcxp eibkxou eibkxou msykuiq
huvmxfh jbe huvmxfh ettc wqtwtva eibkxou
gad ubvug baytyk aahanv ubvug ubvug
msykuiq fpe msykuiq mmg msykuiq nerg
gvppcxp eibkxou nerg nerg eibkxou ubvug
ivdtx wqtwtva wqtwtva rclqxu jbe nerg
dioxc gvppcxp ubvug nerg huvmxfh mmg
eibkxou huvmxfh fpe ivdtx eibkxou rclqxu
dnw eibkxou ivdtx nerg dnw huvmxfh
gvppcxp gvppcxp ettc jbe wqtwtva baytyk
fpe gvppcxp gvppcxp eibkxou jbe aahanv
uckiowh dnw dioxc ivdtx wqtwtva uckiowh
ivdtx fpe ubvug fpe wqtwtva dioxc
huvmxfh fpe dioxc dioxc fpe wqtwtva
jbe baytyk ubvug nerg wqtwtva huvmxfh
aahanv nerg ivdtx gvppcxp ivdtx eibkxou
ubvug mmg aahanv eibkxou ubvug jbe
dnw fpe dioxc aahanv jbe ubvug
eibkxou nerg msykuiq gvppcxp dnw ubvug
rclqxu dioxc wqtwtva mmg mmg ivdtx
huvmxfh rclqxu gvppcxp ettc jbe dnw
gvppcxp mmg dioxc huvmxfh msykuiq mmg
ettc gvppcxp gad dnw wqtwtva eibkxou
wqtwtva fpe nerg jbe dioxc wqtwtva
rclqxu uckiowh mmg msykuiq gvppcxp dioxc
ivdtx wqtwtva gvppcxp ettc dnw nerg
huvmxfh ivdtx fpe ubvug jbe ivdtx
msykuiq msykuiq dnw ivdtx huvmxfh uckiowh
dnw mmg ubvug jbe jbe ubvug
dnw dnw mmg nerg gad dioxc
wqtwtva huvmxfh mmg dnw gad ubvug
dnw ivdtx gad baytyk aahanv wqtwtva
mmg mmg dnw dnw huvmxfh mmg
gvppcxp gvppcxp msykuiq huvmxfh dnw ettc
aahanv dnw ubvug eibkxou ivdtx gvppcxp
nerg gad gvppcxp mmg dioxc dioxc
gad jbe gvppcxp baytyk uckiowh huvmxfh
ubvug dioxc gad uckiowh jbe ubvug
ubvug eibkxou dnw ettc uckiowh dnw
baytyk ivdtx wqtwtva wqtwtva rclqxu ivdtx
jbe mmg wqtwtva gvppcxp aahanv dioxc
fpe ubvug dnw huvmxfh msykuiq gvppcxp
ubvug uckiowh mmg ivdtx ivdtx gvppcxp
ivdtx gad ivdtx nerg jbe baytyk
gad ivdtx gvppcxp ubvug gvppcxp uckiowh
jbe eibkxou wqtwtva dioxc rclqxu gvppcxp
nerg ettc nerg mmg mmg ettc
rclqxu ettc eibkxou wqtwtva gvppcxp huvmxfh
rclqxu jbe wqtwtva msykuiq ubvug gvppcxp
dioxc aahanv eibkxou nerg jbe ivdtx
rclqxu msykuiq dnw ettc gvppcxp aahanv
dioxc ivdtx rclqxu dnw wqtwtva ubvug
dioxc rclqxu dnw msykuiq jbe fpe
ubvug jbe uckiowh ivdtx uckiowh ubvug
wqtwtva wqtwtva nerg dioxc baytyk eibkxou
eibkxou rclqxu baytyk ivdtx uckiowh gad
ettc ivdtx aahanv huvmxfh baytyk ivdtx
ubvug rclqxu dnw rclqxu msykuiq msykuiq
jbe ubvug uckiowh uckiowh rclqxu ettc
gvppcxp uckiowh baytyk nerg gad fpe
dioxc aahanv nerg nerg mmg huvmxfh
mmg jbe uckiowh fpe baytyk ubvug
eibkxou ubvug dioxc dioxc ivdtx uckiowh
aahanv baytyk eibkxou baytyk msykuiq jbe
rclqxu nerg nerg aahanv baytyk wqtwtva
gvppcxp rclqxu baytyk jbe ivdtx wqtwtva
fpe nerg fpe huvmxfh gvppcxp uckiowh
fpe nerg rclqxu gvppcxp fpe jbe
dnw gvppcxp ettc uckiowh ivdtx mmg
eibkxou wqtwtva aahanv nerg nerg jbe
msykuiq ubvug baytyk jbe msykuiq fpe
aahanv uckiowh dioxc rclqxu nerg baytyk
dioxc gvppcxp gvppcxp nerg msykuiq uckiowh
eibkxou msykuiq mmg ivdtx rclqxu mmg
ettc ivdtx msykuiq dnw fpe uckiowh
jbe gvppcxp uckiowh wqtwtva dnw ivdtx
gvppcxp dnw huvmxfh gvppcxp baytyk ivdtx
rclqxu gad rclqxu nerg jbe baytyk
ivdtx gad baytyk aahanv wqtwtva gvppcxp
gad ubvug nerg jbe gad wqtwtva
uckiowh wqtwtva fpe aahanv jbe baytyk
ettc ivdtx eibkxou aahanv fpe fpe
gvppcxp dnw rclqxu jbe dioxc ivdtx
uckiowh nerg mmg uckiowh huvmxfh aahanv
gad ubvug ettc baytyk rclqxu baytyk
dioxc eibkxou ettc ivdtx dioxc msykuiq
mmg nerg dnw dnw ettc msykuiq
msykuiq ivdtx aahanv dioxc aahanv gad
gad huvmxfh fpe ubvug ubvug nerg
ettc wqtwtva gad msykuiq nerg ettc
huvmxfh aahanv wqtwtva jbe wqtwtva uckiowh
jbe ubvug uckiowh jbe dnw ettc
ivdtx jbe aahanv msykuiq msykuiq baytyk
ivdtx mmg ubvug rclqxu jbe msykuiq
msykuiq mmg ivdtx nerg gvppcxp baytyk
huvmxfh wqtwtva wqtwtva gvppcxp dnw dnw
dnw msykuiq eibkxou ettc ubvug aahanv
gad ettc rclqxu huvmxfh nerg gvppcxp
baytyk aahanv fpe gad nerg ivdtx
rclqxu wqtwtva jbe dnw gvppcxp eibkxou
uckiowh gvppcxp wqtwtva baytyk eibkxou fpe
wqtwtva ubvug jbe aahanv dnw dnw
ubvug aahanv eibkxou jbe ivdtx aahanv
rclqxu jbe dnw aahanv aahanv wqtwtva
baytyk ivdtx wqtwtva uckiowh nerg nerg
gvppcxp msykuiq eibkxou ettc baytyk gad
ubvug ivdtx ubvug ettc dnw ubvug
uckiowh wqtwtva gvppcxp msykuiq gad eibkxou
aahanv gvppcxp ubvug nerg gad gvppcxp
baytyk mmg mmg gad gvppcxp ivdtx
gad nerg uckiowh wqtwtva mmg wqtwtva
nerg eibkxou gvppcxp baytyk gad fpe
ivdtx baytyk fpe aahanv baytyk jbe
jbe fpe mmg ettc ubvug mmg
ettc gad dnw uckiowh gvppcxp uckiowh
fpe fpe ettc wqtwtva rclqxu ivdtx
gvppcxp nerg aahanv msykuiq fpe dnw
aahanv uckiowh msykuiq nerg uckiowh huvmxfh
jbe jbe gvppcxp dioxc msykuiq aahanv
eibkxou ivdtx ettc mmg nerg ubvug
rclqxu huvmxfh ettc aahanv huvmxfh dioxc
dioxc ettc eibkxou uckiowh ubvug gad
rclqxu uckiowh eibkxou jbe rclqxu ubvug
jbe dnw ivdtx gad aahanv rclqxu
ettc jbe dnw aahanv jbe msykuiq
gvppcxp gad rclqxu baytyk jbe wqtwtva
nerg jbe nerg eibkxou msykuiq dioxc
gvppcxp ettc gad jbe aahanv eibkxou
baytyk ivdtx baytyk gvppcxp mmg ubvug
ivdtx baytyk ivdtx msykuiq eibkxou ivdtx
gad gvppcxp gad fpe rclqxu nerg
nerg fpe mmg dioxc eibkxou gvppcxp
dioxc uckiowh ubvug rclqxu ettc ettc
jbe rclqxu dnw dioxc nerg gvppcxp
jbe gad dioxc gvppcxp fpe fpe
rclqxu jbe msykuiq nerg ettc jbe
eibkxou gad dioxc dioxc rclqxu dnw
wqtwtva uckiowh eibkxou ubvug wqtwtva gvppcxp
dnw aahanv ettc ubvug jbe ubvug
fpe dioxc gvppcxp fpe aahanv rclqxu
nerg baytyk mmg gvppcxp aahanv huvmxfh
uckiowh gvppcxp ubvug aahanv huvmxfh dioxc
dnw dioxc eibkxou aahanv wqtwtva aahanv
gad wqtwtva wqtwtva baytyk ettc baytyk
uckiowh nerg dnw wqtwtva dnw ettc
rclqxu gvppcxp ivdtx ubvug jbe dioxc
gvppcxp ettc msykuiq dioxc jbe ubvug
dnw baytyk rclqxu msykuiq baytyk ettc
aahanv fpe uckiowh msykuiq fpe gad
gad rclqxu gvppcxp jbe uckiowh aahanv
dnw huvmxfh huvmxfh ivdtx dioxc gvppcxp
gvppcxp gad ivdtx huvmxfh uckiowh nerg
ubvug ettc gvppcxp ettc uckiowh jbe
ivdtx msykuiq mmg dnw wqtwtva huvmxfh
nerg eibkxou rclqxu dioxc aahanv nerg
rclqxu huvmxfh wqtwtva gad ettc ivdtx
ivdtx gvppcxp msykuiq nerg baytyk ivdtx
ivdtx jbe nerg uckiowh aahanv gad
aahanv gvppcxp ivdtx uckiowh aahanv nerg
gad gvppcxp fpe ubvug gad ettc
msykuiq mmg gad dnw eibkxou gvppcxp
ivdtx ubvug dnw huvmxfh aahanv ubvug
wqtwtva eibkxou jbe dnw ivdtx wqtwtva
baytyk huvmxfh baytyk mmg aahanv fpe
nerg ettc msykuiq wqtwtva dioxc nerg
ivdtx ivdtx eibkxou gad huvmxfh aahanv
rclqxu aahanv huvmxfh msykuiq uckiowh aahanv
uckiowh mmg fpe nerg msykuiq dioxc
huvmxfh gad aahanv eibkxou aahanv nerg
fpe msykuiq uckiowh jbe uckiowh huvmxfh
wqtwtva uckiowh dnw eibkxou ivdtx nerg
gvppcxp ettc huvmxfh jbe aahanv ivdtx
huvmxfh aahanv wqtwtva gvppcxp aahanv nerg
aahanv dnw nerg ivdtx aahanv ivdtx
nerg ivdtx baytyk mmg ubvug fpe
dnw nerg dnw msykuiq aahanv ettc
gad ivdtx eibkxou dnw msykuiq msykuiq
fpe msykuiq mmg fpe jbe mmg
nerg huvmxfh ettc nerg nerg gvppcxp
dioxc baytyk wqtwtva gvppcxp aahanv rclqxu
eibkxou gad rclqxu uckiowh aahanv ubvug
ivdtx dioxc aahanv msykuiq aahanv dnw
rclqxu mmg ubvug ubvug ettc jbe
baytyk baytyk nerg wqtwtva huvmxfh rclqxu
msykuiq rclqxu baytyk baytyk gvppcxp msykuiq
dioxc baytyk huvmxfh rclqxu nerg uckiowh
ettc mmg ubvug huvmxfh gvppcxp gvppcxp
ettc ivdtx jbe msykuiq eibkxou aahanv
eibkxou huvmxfh eibkxou baytyk msykuiq huvmxfh
ubvug gvppcxp gad gad ubvug wqtwtva
dioxc msykuiq ivdtx aahanv uckiowh aahanv
huvmxfh ubvug wqtwtva fpe fpe ivdtx
aahanv msykuiq gad huvmxfh jbe rclqxu
dioxc dnw aahanv dnw baytyk huvmxfh
eibkxou dnw wqtwtva aahanv dnw rclqxu
eibkxou aahanv ettc uckiowh gad huvmxfh
eibkxou ettc baytyk eibkxou aahanv nerg
mmg jbe msykuiq ubvug fpe dioxc
gad ettc gad ettc ivdtx gad
gad wqtwtva wqtwtva ivdtx gad aahanv
gvppcxp nerg fpe uckiowh ivdtx fpe
msykuiq dnw rclqxu baytyk ubvug nerg
msykuiq mmg jbe wqtwtva mmg msykuiq
msykuiq eibkxou dnw nerg ivdtx huvmxfh
eibkxou dioxc uckiowh huvmxfh wqtwtva msykuiq
uckiowh msykuiq baytyk fpe uckiowh ivdtx
baytyk rclqxu huvmxfh ivdtx baytyk baytyk
gvppcxp uckiowh uckiowh gvppcxp uckiowh mmg
dioxc ettc rclqxu uckiowh rclqxu dnw
aahanv msykuiq ubvug dnw eibkxou dioxc
huvmxfh msykuiq mmg ivdtx fpe ettc
eibkxou jbe jbe huvmxfh dioxc ettc
gad gad gad huvmxfh gvppcxp gvppcxp
dnw huvmxfh baytyk dioxc nerg eibkxou
uckiowh ivdtx eibkxou huvmxfh nerg aahanv
ubvug jbe eibkxou aahanv fpe mmg
mmg wqtwtva gad ivdtx baytyk baytyk
dnw dioxc huvmxfh wqtwtva huvmxfh nerg
gvppcxp aahanv fpe ubvug baytyk baytyk
dioxc msykuiq baytyk uckiowh ivdtx jbe
ivdtx ettc msykuiq mmg msykuiq gad
aahanv baytyk dnw ivdtx jbe gad
gvppcxp nerg uckiowh rclqxu mmg eibkxou
msykuiq mmg jbe fpe wqtwtva ubvug
ubvug ubvug jbe mmg ettc gad
mmg wqtwtva dnw msykuiq huvmxfh nerg
ettc ettc dioxc baytyk fpe eibkxou
uckiowh dioxc ettc uckiowh dnw gvppcxp
jbe ubvug jbe aahanv gad gad
dnw msykuiq mmg wqtwtva eibkxou uckiowh
dnw huvmxfh baytyk mmg fpe nerg
gad msykuiq rclqxu gad wqtwtva baytyk
huvmxfh baytyk wqtwtva gvppcxp gvppcxp uckiowh
fpe baytyk nerg nerg rclqxu ubvug
rclqxu ivdtx ettc fpe dnw uckiowh
baytyk ettc msykuiq gad gad dioxc
ettc huvmxfh ettc nerg fpe eibkxou
wqtwtva fpe aahanv gvppcxp gvppcxp ivdtx
ubvug jbe baytyk wqtwtva rclqxu mmg
ubvug baytyk huvmxfh gvppcxp baytyk mmg
ettc gad msykuiq huvmxfh msykuiq uckiowh
rclqxu baytyk uckiowh uckiowh fpe dioxc
ivdtx dioxc gvppcxp fpe mmg aahanv
gad huvmxfh baytyk dnw huvmxfh eibkxou
dioxc gad gvppcxp mmg mmg ettc
msykuiq gad ettc fpe mmg wqtwtva
dnw ettc wqtwtva dnw rclqxu ubvug
huvmxfh wqtwtva msykuiq rclqxu ubvug aahanv
msykuiq uckiowh gvppcxp wqtwtva gvppcxp eibkxou
huvmxfh gad mmg baytyk gad huvmxfh
wqtwtva eibkxou msykuiq gvppcxp jbe uckiowh
jbe gvppcxp dnw huvmxfh ettc fpe
ettc nerg huvmxfh aahanv fpe dioxc
jbe dnw gvppcxp dioxc dnw msykuiq
rclqxu huvmxfh msykuiq jbe dnw mmg
nerg ubvug eibkxou mmg dioxc gvppcxp
dnw ettc aahanv ivdtx gvppcxp ivdtx
wqtwtva aahanv ettc gvppcxp msykuiq fpe
gad gad aahanv ivdtx uckiowh eibkxou
ivdtx aahanv ettc gad huvmxfh mmg
uckiowh nerg mmg huvmxfh nerg jbe
ivdtx jbe dnw gad msykuiq ubvug
uckiowh eibkxou gad jbe ivdtx eibkxou
wqtwtva rclqxu eibkxou jbe fpe ivdtx
dioxc aahanv mmg gad gvppcxp aahanv
rclqxu baytyk gad ubvug ivdtx jbe
baytyk ubvug dioxc ivdtx msykuiq baytyk
dioxc rclqxu gad msykuiq ubvug dnw
dioxc nerg nerg rclqxu huvmxfh dnw
gad fpe mmg aahanv fpe ettc
ettc fpe huvmxfh nerg wqtwtva wqtwtva
gad ubvug ettc mmg jbe jbe
ivdtx dnw baytyk fpe fpe dioxc
fpe ettc mmg eibkxou aahanv aahanv
jbe eibkxou jbe eibkxou baytyk aahanv
fpe rclqxu ubvug ubvug fpe eibkxou
nerg fpe msykuiq ivdtx mmg dnw
wqtwtva jbe eibkxou ubvug aahanv huvmxfh
jbe ubvug rclqxu ubvug mmg ettc
jbe uckiowh ubvug aahanv baytyk uckiowh
gvppcxp dnw dnw nerg jbe mmg
gad jbe huvmxfh baytyk ivdtx eibkxou
gvppcxp nerg aahanv jbe ettc gvppcxp
gvppcxp aahanv ubvug dioxc ettc mmg
ettc eibkxou fpe aahanv ubvug wqtwtva
ubvug huvmxfh msykuiq aahanv gad nerg
dnw ettc jbe dnw uckiowh uckiowh
gad huvmxfh gvppcxp rclqxu nerg gvppcxp
aahanv huvmxfh ettc dnw gvppcxp jbe
aahanv fpe jbe msykuiq msykuiq gad
mmg aahanv nerg nerg rclqxu gvppcxp
eibkxou dioxc mmg dioxc nerg eibkxou
gvppcxp huvmxfh ivdtx ettc gad ettc
ettc ettc jbe wqtwtva dioxc fpe
gad uckiowh ivdtx nerg wqtwtva dioxc
rclqxu wqtwtva dioxc eibkxou ivdtx eibkxou
jbe eibkxou mmg huvmxfh nerg dnw
ubvug gad baytyk baytyk wqtwtva huvmxfh
ubvug baytyk uckiowh huvmxfh ivdtx rclqxu
dioxc gvppcxp baytyk huvmxfh gvppcxp nerg
nerg fpe mmg ubvug jbe ubvug
gad aahanv ettc mmg nerg baytyk
gad huvmxfh jbe gad huvmxfh ubvug
dioxc jbe ivdtx mmg dnw eibkxou
dnw dnw wqtwtva nerg dioxc ubvug
rclqxu huvmxfh msykuiq baytyk gvppcxp nerg
eibkxou huvmxfh dioxc gad ivdtx rclqxu
mmg fpe nerg msykuiq wqtwtva aahanv
aahanv gad jbe uckiowh dioxc huvmxfh
baytyk jbe uckiowh ivdtx dioxc ubvug
ettc mmg msykuiq ivdtx gad ubvug
wqtwtva nerg eibkxou fpe huvmxfh ubvug
rclqxu aahanv uckiowh gad fpe ubvug
rclqxu gad uckiowh ivdtx dnw eibkxou
baytyk rclqxu ubvug dnw huvmxfh huvmxfh
dioxc ettc gad dioxc msykuiq nerg
dioxc dnw dnw ivdtx dnw baytyk
nerg gvppcxp rclqxu rclqxu gvppcxp jbe
fpe ettc rclqxu dnw dioxc mmg
dioxc dioxc dnw dioxc wqtwtva jbe
uckiowh gad eibkxou ettc jbe uckiowh
gad ubvug aahanv msykuiq baytyk nerg
mmg mmg ettc dnw wqtwtva jbe
rclqxu eibkxou rclqxu jbe gad jbe
ivdtx mmg jbe nerg aahanv ivdtx
gvppcxp wqtwtva huvmxfh huvmxfh jbe eibkxou
gad mmg fpe ettc baytyk rclqxu
rclqxu fpe wqtwtva gvppcxp rclqxu eibkxou
eibkxou jbe uckiowh nerg fpe ivdtx
dioxc baytyk gvppcxp huvmxfh aahanv mmg
gvppcxp ettc uckiowh mmg jbe gad
msykuiq ivdtx fpe huvmxfh rclqxu dioxc
uckiowh fpe nerg eibkxou dnw ivdtx
aahanv ettc msykuiq dioxc aahanv dioxc
gad msykuiq huvmxfh rclqxu ivdtx msykuiq
nerg dnw gvppcxp huvmxfh gad fpe
baytyk uckiowh mmg uckiowh dioxc mmg
jbe uckiowh dnw baytyk jbe huvmxfh
aahanv baytyk mmg wqtwtva ettc aahanv
uckiowh fpe dnw nerg ubvug ubvug
rclqxu ivdtx dioxc gvppcxp rclqxu mmg
fpe dnw fpe aahanv ubvug baytyk
gvppcxp baytyk wqtwtva rclqxu dioxc rclqxu
eibkxou mmg wqtwtva rclqxu gvppcxp fpe
mmg rclqxu huvmxfh gvppcxp mmg jbe
mmg aahanv gvppcxp dnw aahanv nerg
ettc gvppcxp ettc gvppcxp gvppcxp dioxc
ubvug dnw ettc uckiowh nerg nerg
aahanv mmg fpe ivdtx ivdtx msykuiq
mmg wqtwtva uckiowh gvppcxp nerg msykuiq
gad fpe jbe mmg baytyk rclqxu
eibkxou ivdtx uckiowh aahanv huvmxfh rclqxu
aahanv rclqxu dnw rclqxu jbe uckiowh
dnw eibkxou eibkxou dnw wqtwtva eibkxou
fpe uckiowh mmg gvppcxp dnw ettc
aahanv eibkxou gad eibkxou gvppcxp uckiowh
mmg gad rclqxu nerg mmg eibkxou
nerg mmg fpe ubvug fpe uckiowh
ettc rclqxu jbe msykuiq rclqxu dioxc
fpe ubvug jbe eibkxou wqtwtva huvmxfh
mmg ivdtx rclqxu gvppcxp mmg dnw
aahanv ettc wqtwtva dnw huvmxfh dnw
dioxc dnw eibkxou huvmxfh huvmxfh jbe
huvmxfh jbe mmg ivdtx uckiowh ubvug
huvmxfh nerg ubvug gvppcxp baytyk fpe
gvppcxp mmg huvmxfh mmg aahanv dnw
ettc aahanv mmg eibkxou rclqxu ettc
uckiowh gvppcxp rclqxu baytyk nerg aahanv
rclqxu gad aahanv jbe ubvug dioxc
dnw mmg dioxc dnw eibkxou huvmxfh
wqtwtva gad nerg huvmxfh jbe huvmxfh
gad mmg uckiowh nerg gvppcxp aahanv
rclqxu msykuiq jbe uckiowh ubvug jbe
dioxc eibkxou jbe dioxc ettc eibkxou
rclqxu uckiowh aahanv dnw rclqxu aahanv
dioxc dioxc fpe huvmxfh gvppcxp nerg
uckiowh dnw rclqxu ivdtx msykuiq msykuiq
eibkxou dnw dnw rclqxu ettc ubvug
mmg rclqxu aahanv ivdtx uckiowh msykuiq
nerg ubvug rclqxu gad nerg jbe
huvmxfh fpe ivdtx eibkxou eibkxou ettc
msykuiq ettc baytyk ubvug eibkxou gad
ubvug msykuiq huvmxfh baytyk dnw huvmxfh
uckiowh wqtwtva gvppcxp baytyk fpe nerg
ivdtx gad dnw ubvug huvmxfh baytyk
gad ivdtx dioxc jbe huvmxfh dnw
fpe mmg nerg gad huvmxfh dioxc
baytyk wqtwtva dnw ubvug dioxc ettc
dioxc mmg aahanv fpe aahanv ivdtx
msykuiq mmg mmg uckiowh uckiowh baytyk
aahanv fpe baytyk baytyk mmg ubvug
fpe gad uckiowh mmg ettc ettc
dioxc eibkxou rclqxu jbe fpe huvmxfh
nerg gad ettc mmg mmg mmg
rclqxu ivdtx uckiowh dioxc uckiowh nerg
uckiowh uckiowh ubvug dnw wqtwtva ivdtx
dnw dioxc aahanv gad mmg eibkxou
gvppcxp fpe gad ettc mmg jbe
nerg uckiowh gvppcxp gad uckiowh gad`;